engines:
  rubocop:
    enabled: true
  eslint:
    enabled: true
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - ruby
      - javascript
  markdownlint:
    enabled: true
ratings:
  paths:
  - "**.js"
  - "**.rb"
  - "**.css"
  - "**.json"
  - "**.md"
exclude_paths:
  - node_modules/**
  - examplefiles/**
  - dist/**
  - img/**
  - "src/viz.js"
