language: 
  node_js
  ruby
node_js:
  - "5"
  - "4"

before_script:
  - npm install -g gulp
  - gulp
  - node dist/server.js &
  - sleep 2
script: 
  mocha testcase.js

addons:
  sauce_connect: true
